[project]
name = "htmx-table"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.128.0",
    "jinja2>=3.1.6",
    "orjson>=3.11.5",
    "python-multipart>=0.0.21",
    "uvicorn>=0.40.0",
]
